version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
      - echo Installing Yarn...
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Testing...
      - ls
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
